---
Name: cataloguefrontendconfig
After:
  - '#catalogueconfig'
---
SilverStripe\Control\Controller:
  extensions:
    - SilverCommerce\CatalogueFrontend\Extensions\ControllerExtension
SilverCommerce\CatalogueAdmin\Model\CatalogueProduct:
  extensions:
    - SilverCommerce\CatalogueFrontend\Extensions\CatalogueExtension
SilverCommerce\CatalogueAdmin\Model\CatalogueCategory:
  extensions:
    - SilverCommerce\CatalogueFrontend\Extensions\CatalogueExtension
    - SilverCommerce\CatalogueFrontend\Extensions\CategoryExtension
SilverCommerce\CatalogueAdmin\Model\ProductTag:
  extensions:
    - SilverCommerce\CatalogueFrontend\Extensions\ProductTagExtension
---
Only:
  moduleexists: 'silvercommerce/shoppingcart'
---
SilverCommerce\CatalogueFrontend\Control\CatalogueController:
  extensions:
    - SilverCommerce\CatalogueFrontend\Extensions\AddToCartExtension

---
Only:
  moduleexists: 'hubertusanton/silverstripe-seo'
---
# Automatically add SEO extensions to categorys and products if installed 
SilverCommerce\CatalogueAdmin\Model\CatalogueProduct:
  extensions:
    - Hubertusanton\SilverStripeSeo\SeoObjectExtension
SilverCommerce\CatalogueAdmin\Model\CatalogueCategory:
  extensions:
    - Hubertusanton\SilverStripeSeo\SeoObjectExtension